
services:
  backend-docker:
    container_name: backend-docker
    build: 
      context: /backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8080:80

  mysql_db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kpsm
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      
  frontend:
    container_name: frontend-docker
    build: 
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - "9000:80"